babysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'babysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^diapers/', include('diapers.urls', namespace="diapers")),
    url(r'^$', include('diapers.urls', namespace="diapers")),
    url(r'^admin/', include(admin.site.urls)),
   
]

diapers/urls.py
from django.conf.urls import url
from django.contrib.auth import views


from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add', views.add, name="add"),
    url(r'^login/', 'django.contrib.auth.views.login', name='login'),
    url(r'^logout/', 'django.contrib.auth.views.logout'),
]

diapers/models.py
from django.db import models

class Diaper(models.Model):
    change_date = models.DateTimeField('date published')
    is_wet = models.BooleanField(default=False)
    is_dirty = models.BooleanField(default=False)
    note = models.CharField(max_length=200)
    def __unicode__(self):
	typestr = ''
        if self.is_wet:
		typestr += 'Wet'
        if self.is_dirty:
		if len(typestr) != 0:
			typestr += ' '
		typestr += 'Dirty'
	return "%s: %s %s" % (self.change_date, typestr, self.note)
	

# Create your models here.

diapers/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.utils import timezone
from django.template import RequestContext, loader
from django.shortcuts import render
from django.core.urlresolvers import reverse
import time
import datetime 
from .models import Diaper


# Create your views here.
def index(request):
    today = datetime.datetime.today()
    datestr = request.GET.get('date',  '%s-%s-%s' % (today.year, today.month, today.day))
    (year,month,day) = datestr.split('-')
    tmp = datetime.datetime(int(year),int(month),int(day))
    prevdate = tmp - datetime.timedelta(days=1)
    nextdate = tmp + datetime.timedelta(days=1)
    prevstr = "%s-%s-%s" % (prevdate.year, prevdate.month, prevdate.day)
    nextstr = ''
    if (nextdate <= today):
    	nextstr = "%s-%s-%s" % (nextdate.year, nextdate.month, nextdate.day)
    diapers_today = Diaper.objects.filter(change_date__year=year, 
                                          change_date__month=month,
                                          change_date__day=day)
    diapers_wet = 0
    diapers_dirty = 0
    for diaper in diapers_today:
        if diaper.is_wet:
            diapers_wet += 1
        if diaper.is_dirty:
            diapers_dirty += 1
    template = loader.get_template('diapers/index.html')
    context = RequestContext(request, {
	'diaper_list': diapers_today,
        'diapers_wet': diapers_wet,
        'diapers_dirty' : diapers_dirty,
        'date_str': datestr,
        'prevstr': prevstr,
        'nextstr':nextstr,
    })
    return HttpResponse(template.render(context))

def add(request):
    posties = request.POST
    error_code = ""
    if not posties.has_key('change_time'):
	# error here
        error_code += " missing date "
    if not posties.has_key("diaper_type_wet") and not posties.has_key("diaper_type_dirty"):
        error_code += " missing type "
    if (error_code != ""):
	#redicect...
        return render(request, 'diapers/add.html', {
            'error_message': error_code
        })
    
    change_timestruct = time.strptime(posties['change_time'], "%Y-%m-%d %H:%M")
    change_time = datetime.datetime(change_timestruct[0], change_timestruct[1],
	change_timestruct[2], change_timestruct[3], change_timestruct[4])
    wet = posties.has_key("diaper_type_wet")
    dirty = posties.has_key("diaper_type_dirty")
    new_diaper = Diaper(change_date = change_time, is_wet = wet, is_dirty = dirty)
    new_diaper.save()
    return HttpResponseRedirect(reverse('diapers:index'))

diapers/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>My Project</title>
    </head>

    <body>
    {% block content %}{% endblock %}
    </body>
</html>

diapers/templates/diapers/add.html
<h1>Add A Diaper Change!</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'diapers:add' %}" method="post">
{% csrf_token %}
Change Time:<input type="text" name="change_time" value="{% now "Y-m-d H:i" %}">
<br>
Wet?:<input type="checkbox" value="is_wet" name="diaper_type_wet"><br>
Dirty?:<input type="checkbox" value="is_dirty" name="diaper_type_dirty"><br>
<input type="submit" value="Adde" />
</form>

diapers/templates/diapers/index.html
{% load tz %}
<title>Diapers for: {{ date_str}} </title>
<a href={% url 'diapers:index' %}?date={{prevstr}}>previous_day</a>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<a href={%url 'diapers:add' %}>Add New</a>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
{% if nextstr != '' %} 
<a href={% url 'diapers:index' %}?date={{nextstr}}>next day</a>
{% else %}
next
{%endif %}
<br>
<br>
<br>
<br>
{% if diapers_wet and diapers_dirty %}
wet: {{ diapers_wet }} <br>
dirtry: {{ diapers_dirty}} <br>
{% else %}
no wet or dirty found!<br>
{% endif %}
{% if diaper_list %}
    <ul>
    {% for diaper in diaper_list %}
    {% localtime on %}
    
        <li><a href="/polls/{{ diaper.id }}/">{{ diaper.change_date }}
	{% if diaper.is_wet %}
          WET
        {% endif %}
	{% if diaper.is_dirty %}
          DIRTY 
        {% endif %}
</a></li>
    {% endlocaltime  %}
    {% endfor %}
    </ul>
{% else %}
    <p>No diapers are available.</p>
{% endif %}